# Generated by Django 4.2.4 on 2023-08-23 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0008_alter_ticketmovie_movie_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name_client', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.CharField(max_length=10)),
                ('email_client', models.EmailField(blank=True, max_length=254, null=True)),
                ('link_back', models.CharField(max_length=250)),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.PositiveIntegerField()),
                ('amount', models.CharField(max_length=10)),
                ('date_payment', models.DateTimeField(auto_now=True)),
                ('movie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.movie')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.transactions')),
            ],
        ),
    ]
