# Generated by Django 4.2.4 on 2023-08-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactions_datetime_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
