# Generated by Django 4.2.4 on 2023-08-19 05:31

from django.db import migrations, models
import django.db.models.deletion
import movie.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_room', models.CharField(max_length=100, validators=[movie.validators.check_name_word_and_number])),
                ('quantity_person', models.PositiveIntegerField()),
                ('address_room', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_movie', models.ImageField(upload_to='image_movie/')),
                ('director_movie', models.CharField(max_length=150)),
                ('price_ticket', models.CharField(max_length=10)),
                ('genre_movie', models.CharField(max_length=100)),
                ('name_movie', models.CharField(max_length=100, validators=[movie.validators.check_name_word_and_number])),
                ('time_movie', models.TimeField()),
                ('datetime_start', models.DateTimeField()),
                ('about_movie', models.TextField(blank=True, null=True)),
                ('room_movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.room')),
            ],
        ),
    ]
