# Generated by Django 4.2.4 on 2023-08-27 22:44

from django.db import migrations, models
import django.db.models.deletion
import movie.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission_sell', models.BooleanField(default=True)),
                ('image_movie', models.ImageField(upload_to='image_movie/')),
                ('director_movie', models.CharField(max_length=150)),
                ('price_ticket', models.CharField(max_length=10, validators=[movie.validators.is_number])),
                ('genre_movie', models.CharField(max_length=100)),
                ('name_movie', models.CharField(max_length=100, validators=[movie.validators.check_name_word_and_number])),
                ('time_movie', models.TimeField()),
                ('datetime_start', models.DateTimeField()),
                ('about_movie', models.TextField(blank=True, null=True)),
                ('registered_ticket', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_room', models.CharField(max_length=100, unique=True, validators=[movie.validators.check_name_word_and_number])),
                ('quantity_person', models.PositiveIntegerField()),
                ('address_room', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_bought', models.DateTimeField()),
                ('key_data', models.CharField(max_length=50, unique=True)),
                ('encode_data', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='room_movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movie.room'),
        ),
    ]
