# Generated by Django 4.2.4 on 2023-08-19 06:53

from django.db import migrations, models
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_room',
            field=models.CharField(max_length=100, unique=True, validators=[movie.validators.check_name_word_and_number]),
        ),
    ]
