# Generated by Django 4.2.4 on 2023-08-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_room_address_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address_room',
            field=models.TextField(blank=True, null=True),
        ),
    ]
