# Generated by Django 4.2.4 on 2023-08-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import movie.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0004_alter_room_address_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='registered_ticket',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price_ticket',
            field=models.CharField(max_length=10, validators=[movie.validators.is_number]),
        ),
        migrations.CreateModel(
            name='TicketMovie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_bought', models.DateTimeField(auto_now=True)),
                ('key_data', models.CharField(max_length=50, unique=True)),
                ('encode_data', models.CharField(max_length=300)),
                ('movie_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
