# Generated by Django 4.2.4 on 2023-08-20 07:01

from django.db import migrations, models
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_registered_ticket_alter_movie_price_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='permission_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='seat_reserved',
            field=models.TextField(default=123, validators=[movie.validators.is_number]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmovie',
            name='seat_number',
            field=models.CharField(default='123', max_length=10, validators=[movie.validators.is_number]),
            preserve_default=False,
        ),
    ]
