# Generated by Django 4.2.4 on 2023-08-20 07:07

from django.db import migrations, models
import movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_permission_sell_room_seat_reserved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='seat_reserved',
            field=models.TextField(default='0', editable=False, validators=[movie.validators.is_number]),
        ),
    ]
