#  ---------------------------SUCESS MESSAGE--------------------------------------
SUCCESS_REGISTER = 'با موفقیت ثبت نام شدید .'
SUCESS_SET_PASSWORD = 'پسورد با موفقیت ثبت شد .'
SUCCESS_SEND_SMS = 'کد به شماره تلفن کاربر ارسال شد .'
SUCCESS_CHANGE_PASSWORD = 'پسورد شما با موفقیت تغییر کرد .'
SUCCESS_SEND_TOKEN_FORGET_PASSWORD = 'توکن رمز فراموشی به شماره تلفن شما ارسال شد .'
SUCESS_LOGIN = 'ورود شما با موفقیت انجام شد.'
SUCESS_SET_FORGET_PASSWORD = 'پسورد جدید شما {new_password} است لطفا بعد ورود انرا تغییر دهید .'
SUCESS_COMPLETE_PROFILE = 'پروفایل شمابه درستی کامل شد .'
#  ---------------------------ERROR MESSAGE--------------------------------------
ERROR_EXISTS_TOKEN_OR_STEP_FORM = 'شما مراحل قبلی را با موفقیت طی نکرده اید !'
ERROR_INVALID_PHONE_NUMBER = 'لطفا یک شماره تلفن معتبر وارد کنید !'
ERROR_INVALID_PASSWORD = 'رمز عبور حداقل باید ۸ کاراکتر باشد !'
ERROR_INVALID_RE_PASSWORD = 'رمز عبور و تکرار ان با هم برابر نیستند !'
ERROR_OLD_PASSWORD_INVALID = 'شما پسورد قدیمی خود را به درستی وارد نکرده اید !'
ERROR_AUTHENTICATION_USER = 'کاربری با این اطلاعات وجود ندارد .'
ERROR_SEND_SMS = 'در ارسال پیام مشکلی پیش امده است لطفا دوباره امتحان کنید !'
ERROR_DUPLICATE_PHONE_NUMBER = 'این شماره تلفن قبلا ثبت شده است .'
ERROR_NOT_EXISTS_PHONE_NUMBER = 'این شماره تلفن در سایت ثبت نام نکرده است .'
ERROR_INVALID_TOKEN_LOGIN = 'توکن که شما وارد کردید صحیح نیست !'
ERROR_INVALID_URL = 'صفحه ای یافت نشد !'
ERROR_SET_PASSWORD_FOR_FIRST = 'شما قبلا این قسمت را کامل کرده اید !'
ERROR_LOGIN_USER = 'پسورد یا نام کاربری اشتباه است !'
ERROR_LIMIT_SIZE_PHOTO = 'حجم عکس انتخابی باید کمتر از دو مگابایت باشد !'
#  ---------------------------OTHER MESSAGE--------------------------------------
SEND_TOKEN_TO_USER = 'کد ورود شما به سایت {token} است .'
